<a href="https://colab.research.google.com/github/biopharma26/PracticeNotebooks/blob/main/6_1_Clinical_Genomics_Variant_Prioritization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lab Session 1: Clinical Genomics and Precision Medicine
This notebook guides MSc students through clinical variant annotation filtering and prioritization using Python.

### 1. Environment Setup & Dependencies
Install and import standard libraries for handling tabular genomic variant data.

In [1]:
import pandas as pd
import numpy as np

print('Libraries imported successfully for Clinical Variant Prioritization.')

Libraries imported successfully for Clinical Variant Prioritization.

### 2. Simulate Clinical VCF / Variant Data
We create a mock dataframe representing annotated variant calls from an exome sequencing run.

In [2]:
data = {
    'Gene': ['BRCA1', 'TP53', 'EGFR', 'CFTR', 'TTN'],
    'Variant': ['c.68_69delAG', 'c.743G>A', 'c.2573T>G', 'c.1521_1523delCTT', 'c.1234A>T'],
    'gnomAD_MAF': [0.00001, 0.000, 0.002, 0.005, 0.045],
    'CADD_Phred': [34.5, 28.1, 24.3, 18.2, 5.1],
    'ClinVar': ['Pathogenic', 'Pathogenic', 'Pathogenic', 'Likely Benign', 'Benign']
}

df_variants = pd.DataFrame(data)
df_variants

    Gene            Variant  gnomAD_MAF  CADD_Phred        ClinVar
0  BRCA1       c.68_69delAG     0.00001        34.5     Pathogenic
1   TP53           c.743G>A     0.00000        28.1     Pathogenic
2   EGFR          c.2573T>G     0.00200        24.3     Pathogenic
3   CFTR  c.1521_1523delCTT     0.00500        18.2  Likely Benign
4    TTN          c.1234A>T     0.04500         5.1         Benign

### 3. Variant Filtering Pipeline
Applying strict filtering criteria based on population frequency and pathogenicity prediction scores.

In [3]:
# Filter based on clinical significance thresholds: MAF < 0.01 and CADD > 20
filtered_variants = df_variants[(df_variants['gnomAD_MAF'] < 0.01) & (df_variants['CADD_Phred'] > 20)]
print('Prioritized Pathogenic/Likely Pathogenic Candidates:')
filtered_variants

Prioritized Pathogenic/Likely Pathogenic Candidates:

    Gene       Variant  gnomAD_MAF  CADD_Phred     ClinVar
0  BRCA1  c.68_69delAG     0.00001        34.5  Pathogenic
1   TP53      c.743G>A     0.00000        28.1  Pathogenic
2   EGFR     c.2573T>G     0.00200        24.3  Pathogenic